const A=[
[0,"Jai Ganesh Deva",`Jai Ganesh, Jai Ganesh, Jai Ganesh Deva\nMata Jaki Parvati, Pita Mahadeva\n\nEkadant Dayavant, Char Bhuja Dhari\nMathe Sindoor Sohe, Muse Ki Savari\n\nPan Chadhe, Phool Chadhe, Aur Chadhe Meva\nLadduan Ka Bhog Lage, Sant Kare Seva\n\nAndhan Ko Aankh Det, Kodhin Ko Kaya\nBanjhan Ko Putra Det, Nirdhan Ko Maya\n\nSur Shyam Sharan Aaye, Safal Kije Seva\nMata Jaki Parvati, Pita Mahadeva`,`जय गणेश, जय गणेश, जय गणेश देवा\nमाता जाकी पार्वती, पिता महादेवा\n\nएकदंत दयावंत, चार भुजा धारी\nमाथे सिंदूर सोहे, मूसे की सवारी\n\nपान चढ़े, फूल चढ़े, और चढ़े मेवा\nलड्डुओं का भोग लगे, संत करें सेवा\n\nअंधन को आँख देत, कोढ़िन को काया\nबांझन को पुत्र देत, निर्धन को माया\n\nसूर श्याम शरण आए, सफल कीजे सेवा\nमाता जाकी पार्वती, पिता महादेवा`,`जय गणेश, जय गणेश, जय गणेश देवा\nमाता जाकी पार्वती, पिता महादेवा\n\nएकदंत दयावंत, चार भुजा धारी\nमाथे सिंदूर शोभे, मूषकाची स्वारी\n\nपान चढे, फूल चढे, आणि चढे मेवा\nलाडवांचा भोग लागे, संत करती सेवा\n\nअंधांना डोळे देई, कोढ्यांना काया\nवांझांना पुत्र देई, निर्धनांना माया\n\nसूर श्याम शरण आले, सफल कीजे सेवा\nमाता जाकी पार्वती, पिता महादेवा`],
[1,"Sukhkarta Dukhharta",`Sukhkarta Dukhharta Varta Vighnachi\nNurvi Purvi Prema Krupa Jayachi\nSarvangi Sundar Uti Shendurachi\nKanthi Jhalke Mal Mukta Phalanchi\n\nJai Dev Jai Dev Jai Mangal Murti\nDarshan Maatre Man Kaamna Purti\nJai Dev Jai Dev`,`सुखकर्ता दुःखहर्ता वार्ता विघ्नाची\nनुरवी पुरवी प्रेम कृपा जयाची\nसर्वांगी सुंदर उटी शेंदुराची\nकंठी झळके माळ मुक्ताफळांची\n\nजय देव जय देव जय मंगलमूर्ती\nदर्शन मात्रे मनःकामना पूर्ति\nजय देव जय देव`,`सुखकर्ता दुःखहर्ता वार्ता विघ्नाची\nनुरवी पुरवी प्रेम कृपा जयाची\nसर्वांगी सुंदर उटी शेंदुराची\nकंठी झळके माळ मुक्ताफळांची\n\nजय देव जय देव जय मंगलमूर्ती\nदर्शनमात्रे मनःकामना पूर्ती\nजय देव जय देव`],
[2,"Shendur Lal Chadhayo",`Shendur Lal Chadhayo Achha Gajmukh Ko\nDondil Lal Biraje Sut Gauriharko\nHath Liye Gud Laddu Sai Survar Ko\nMahima Kahe Na Jay Lagat Hoon Pad Ko\n\nJai Jai Shri Ganraj Vidya Sukhdata\nDhanya Tumhara Darshan Mera Man Ramata\nJai Dev Jai Dev`,`शेंदूर लाल चढ़ायो अच्छा गजमुख को\nदोंदिल लाल बिराजे सुत गौरीहर को\nहाथ लिए गुड़ लड्डू साईं सुरवर को\nमहिमा कहे न जाए लागत हूँ पद को\n\nजय जय श्री गणराज विद्या सुखदाता\nधन्य तुम्हारा दर्शन मेरा मन रमता\nजय देव जय देव`,`शेंदूर लाल चढायो अच्छा गजमुख को\nदोंदिल लाल विराजे सुत गौरीहर को\nहात घेऊनी गूळ लाडू साईं सुरवर को\nमहिमा वर्णिता न ये, लागतो चरणांसी\n\nजय जय श्री गणराज विद्या सुखदाता\nधन्य तुझा दर्शन, माझे मन रमता\nजय देव जय देव`],
[3,"Lavthavti Vikrala",`Lavthavti Vikrala Brahmandi Mala\nVishe Kantha Kala Trinetri Jwala\nLavanya Sundar Mastaki Bala\nTethuniya Jal Nirmal Vahe Jhalajhala\n\nJai Dev Jai Dev Jai Shri Shankara\nAarti Ovalu Tuj Karpur Gaurahara\nJai Dev Jai Dev`,`लवथवती विक्राळा ब्रह्मांडी माळा\nविषे कंठ काळा त्रिनेत्री ज्वाळा\nलावण्य सुंदर मस्तकी बाळा\nतेथुनिया जळ निर्मळ वाहे झळझळा\n\nजय देव जय देव जय श्री शंकरा\nआरती ओवाळू तुज कर्पूरगौरा\nजय देव जय देव`,`लवथवती विक्राळा ब्रह्मांडी माळा\nविषे कंठ काळा त्रिनेत्री ज्वाळा\nलावण्य सुंदर मस्तकी बाळा\nतेथुनिया जळ निर्मळ वाहे झळझळा\n\nजय देव जय देव जय श्री शंकरा\nआरती ओवाळू तुज कर्पूरगौरा\nजय देव जय देव`],
[4,"Durge Durghat Bhari",`Durge Durghat Bhari Tujvin Sansari\nAnath Nath Ambe Karuna Vistari\nVari Vari Janm Maranate Vari\nHari Padalo Ata Sankat Nivari\n\nJai Devi Jai Devi Jai Mahishasuramathini\nSurvar Ishvar Varde Taarak Sanjivani\nJai Devi Jai Devi`,`दुर्गे दुर्गट भारी तुजविण संसारी\nअनाथनाथे अंबे करुणा विस्तारी\nवारी वारी जन्ममरणाते वारी\nहरि पडलो आता संकट निवारी\n\nजय देवी जय देवी जय महिषासुरमथिनी\nसुरवर ईश्वर वरदे तारक संजीवनी\nजय देवी जय देवी`,`दुर्गे दुर्गट भारी तुजविण संसारी\nअनाथनाथे अंबे करुणा विस्तारी\nवारी वारी जन्ममरणाते वारी\nहरि पडलो आता संकट निवारी\n\nजय देवी जय देवी जय महिषासुरमथिनी\nसुरवर ईश्वर वरदे तारक संजीवनी\nजय देवी जय देवी`],
[5,"Yei O Vitthale",`Yei O Vitthale, Majhe Mauli Ye\nNidhidhari Vithoba Rakhumai\nPanduranga Vitthala, Rakhumai\n\nYei O Vitthale, Majhe Mauli Ye\nTujvin Majha Koni Nahi\nPanduranga Vitthala, Rakhumai`,`येई ओ विठ्ठले, मेरी माऊली आओ\nहृदय में विराजो विठोबा रखुमाई\nपांडुरंग विठ्ठल, रखुमाई\n\nयेई ओ विठ्ठले, मेरी माऊली आओ\nतुम बिन मेरा कोई नहीं\nपांडुरंग विठ्ठल, रखुमाई`,`येई ओ विठ्ठले, माझे माऊली ये\nहृदयामध्ये विठोबा रखुमाई\nपांडुरंग विठ्ठल, रखुमाई\n\nयेई ओ विठ्ठले, माझे माऊली ये\nतुजविण माझा कोणी नाही\nपांडुरंग विठ्ठल, रखुमाई`],
[6,"Tu Sukhkarta Tu Dukhharta",`Tu Sukhkarta, Tu Dukhharta\nTu Vighnavinashak Mangal Murti\nTujvin Deva Majha Aadhar Nahi\nCharani Tujhya Thevito Matha\n\nJai Dev Jai Dev Jai Ganraj\nMangal Murti Jai Ganraj`,`तू सुखकर्ता, तू दुःखहर्ता\nतू विघ्नविनाशक मंगलमूर्ति\nतुझ बिन देवा मेरा कोई आधार नहीं\nतेरे चरणों में रखता हूँ माथा\n\nजय देव जय देव जय गणराज\nमंगलमूर्ति जय गणराज`,`तू सुखकर्ता, तू दुःखहर्ता\nतू विघ्नविनाशक मंगलमूर्ती\nतुजविण देवा माझा आधार नाही\nचरणी तुझ्या ठेवितो माथा\n\nजय देव जय देव जय गणराज\nमंगलमूर्ती जय गणराज`],
[7,"Om Jai Jagdish Hare",`Om Jai Jagdish Hare\nSwami Jai Jagdish Hare\nBhakt Jano Ke Sankat\nKshan Mein Door Kare\n\nJo Dhyaave Phal Paave\nDukh Vinse Man Ka\nSukh Sampatti Ghar Aave\nKasht Mite Tan Ka\n\nMata Pita Tum Mere\nSharan Gahun Main Kiski\nTum Bin Aur Na Duja\nAas Karun Main Jiski`,`ॐ जय जगदीश हरे\nस्वामी जय जगदीश हरे\nभक्त जनों के संकट\nक्षण में दूर करे\n\nजो ध्यावे फल पावे\nदुःख विनसे मन का\nसुख संपत्ति घर आवे\nकष्ट मिटे तन का\n\nमाता पिता तुम मेरे\nशरण गहूँ मैं किसकी\nतुम बिन और न दूजा\nआस करूँ मैं जिसकी`,`ॐ जय जगदीश हरे\nस्वामी जय जगदीश हरे\nभक्त जनांचे संकट\nक्षणात दूर करे\n\nजो ध्यावे फळ पावे\nदुःख विनसे मनाचे\nसुख संपत्ती घरी येई\nकष्ट मिटती तनाचे\n\nमाता पिता तुम्ही माझे\nशरण जाऊ मी कुणाची\nतुमविण दुसरा नाही\nआस धरू मी कुणाची`],
[8,"Karpur Gauram",`Karpur Gauram Karunavataram\nSansar Saram Bhujagendra Haram\nSada Vasantam Hridayaravinde\nBhavam Bhavani Sahitam Namami`,`कर्पूरगौरं करुणावतारं\nसंसारसारं भुजगेन्द्रहारम्\nसदा वसन्तं हृदयारविन्दे\nभवं भवानीसहितं नमामि`,`कर्पूरगौरं करुणावतारं\nसंसारसारं भुजगेन्द्रहारम्\nसदा वसन्तं हृदयारविंदे\nभवं भवानीसहितं नमामि`],
[9,"Ghalin Lotangan",`Ghalin Lotangan Vandin Charan\nDolyani Pahin Rup Tujhe\nPreme Alingan Anand Pujan\nBhavene Ovalin Mhane Nama\n\nTvamev Mata Cha Pita Tvamev\nTvamev Bandhushcha Sakha Tvamev\nTvamev Vidya Dravinam Tvamev\nTvamev Sarvam Mama Deva Deva\n\nKayena Vacha Manasendriyairva\nBuddhyatmana Va Prakriteh Svabhavat\nKaromi Yadyat Sakalam Parasmai\nNarayanayeti Samarpayami`,`घालीन लोटांगण वंदीन चरण\nडोळ्यांनी पाहीन रूप तुझे\nप्रेमे आलिंगन आनंदे पूजिन\nभावे ओवाळीन म्हणे नामा\n\nत्वमेव माता च पिता त्वमेव\nत्वमेव बन्धुश्च सखा त्वमेव\nत्वमेव विद्या द्रविणं त्वमेव\nत्वमेव सर्वं मम देवदेव\n\nकायेन वाचा मनसेंद्रियैर्वा\nबुद्ध्यात्मना वा प्रकृतेः स्वभावात्\nकरोमि यद्यत् सकलं परस्मै\nनारायणायेति समर्पयामि`,`घालीन लोटांगण वंदीन चरण\nडोळ्यांनी पाहीन रूप तुझे\nप्रेमे आलिंगन आनंदे पूजिन\nभावे ओवाळीन म्हणे नामा\n\nत्वमेव माता च पिता त्वमेव\nत्वमेव बन्धुश्च सखा त्वमेव\nत्वमेव विद्या द्रविणं त्वमेव\nत्वमेव सर्वं मम देवदेव\n\nकायेन वाचा मनसेंद्रियैर्वा\nबुद्ध्यात्मना वा प्रकृतेः स्वभावात्\nकरोमि यद्यत् सकलं परस्मै\nनारायणायेति समर्पयामि`] ]
const names={en:"Ganesh Aarti Book",hi:"गणेश आरती संग्रह",mr:"गणेश आरती संग्रह"};
const intro={en:["Shri Ganesh Aarti","Select an aarti below and read it in your chosen language."],hi:["श्री गणेश आरती","नीचे से कोई आरती चुनें और अपनी चुनी हुई भाषा में पढ़ें।"],mr:["श्री गणेश आरती","खालील आरती निवडा आणि आपल्या निवडलेल्या भाषेत वाचा."]};
const nav=document.querySelector('#nav'),list=document.querySelector('#list'),lang=document.querySelector('#lang');
function render(L){document.documentElement.lang=L;document.querySelector('#headerTitle').textContent=names[L];document.querySelector('#welcomeTitle').textContent=intro[L][0];document.querySelector('#welcomeText').textContent=intro[L][1];lang.value=L;nav.innerHTML='';list.innerHTML='';A.forEach(x=>{const [n,title,en,hi,mr]=x;const b=document.createElement('button');b.textContent=`${n}. ${title}`;b.onclick=()=>document.getElementById(`a${n}`).scrollIntoView({behavior:'smooth'});nav.appendChild(b);const card=document.createElement('article');card.className='aarti';card.id=`a${n}`;card.innerHTML=`<div class="number">AARTI ${n}</div><h3>${[en,hi,mr][0+({en:0,hi:1,mr:2}[L])]}</h3><div class="divider"></div><div class="lyrics"></div><div class="note">॥ श्री गणेशाय नमः ॥</div>`;card.querySelector('.lyrics').textContent=[en,hi,mr][{en:0,hi:1,mr:2}[L]];list.appendChild(card);});}
function openBook(L){localStorage.setItem('aartiLang',L);document.querySelector('#languageScreen').classList.add('hidden');document.querySelector('#bookScreen').classList.remove('hidden');render(L);window.scrollTo(0,0)}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>openBook(b.dataset.lang));lang.onchange=e=>render(e.target.value);document.querySelector('#home').onclick=()=>{document.querySelector('#bookScreen').classList.add('hidden');document.querySelector('#languageScreen').classList.remove('hidden');window.scrollTo(0,0)};
const saved=localStorage.getItem('aartiLang'); if(saved) openBook(saved);
